### ISSUE TITLE
[ MusicMan version 0.1] Audio Files not Detected

### ISSUE THREAD

**Issue by XAMIR555** [ZoidbergZero/MusicMan#4]
#### Project Information
* Repository    :  https://github.com/ZoidbergZero/MusicMan
* Project Name  : MusicMan
* Publisher     :  zoidbergZero

#### Expected behavior

I expected that  my all audio files should be shown in the main page of application

#### Actual behavior

My audio files cannot showing in the application you can see in bug video properly 

#### How to reproduce
*  [ download the letest application ](https://github.com/ZoidbergZero/MusicMan/releases) 
* open the application

* Note the Bug
* Browser/App version:  0.1
* Operating system:  8.0.0

#### GitHub Account
https://github.com/XAMIR555
#### Recording Of The Bug

https://youtu.be/UG3klmi_yP8

####  Logcat 

<pre><code>04-21 02:30:48.457  5228  5228 E AndroidRuntime: FATAL EXCEPTION: main
04-21 02:30:48.457  5228  5228 E AndroidRuntime: Process: com.huawei.autoinstallapkfrommcc, PID: 5228
04-21 02:30:48.457  5228  5228 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.huawei.autoinstallapkfrommcc.InstallAPKReceiver: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3705)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1979)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7425)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:312)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.huawei.autoinstallapkfrommcc.InstallAPKReceiver.onReceive(InstallAPKReceiver.java:42)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3695)
</code></pre>

**Comment by ZoidbergZero** [comment]
Depending on The Number of Songs you have on your Phone, The Initialization of the Songs can take Some Time. I made the Loading of the Songs Asynchronous so the App Runs Normally and updates the List once the Files are Loaded.  For 200 Songs it takes approx 2 Seconds to Load.

In a Future Release i will make the Loading of the Files more Dynamic so you can see the List Updating while the Loading is in Progress.

How Many Songs do you have on your Device Approximately?

**Comment by ZoidbergZero** [comment]
See 8927b4b

Loading Time is Reduced from  ~1 second per 100 Songs to about ~60 miliseconds per 100 Songs.

**Comment by XAMIR555** [comment]
sir but I am waiting from 2 mint but songs cannot show an application if you give me permission i give you video

**Comment by ZoidbergZero** [comment]
Where are the Song Files Stored?

**Comment by XAMIR555** [comment]
[you can see in  the video](https://youtu.be/f3LRlBHy4ro)  my audion songs also available in   "/storage/emulated/0/Download"and "/storage/emulated/0/Music" 
and  the musicman  player also cannot show in open with option  you can in video esily 

####  Logcat 

<pre><code>04-21 02:30:48.457  5228  5228 E AndroidRuntime: FATAL EXCEPTION: main
04-21 02:30:48.457  5228  5228 E AndroidRuntime: Process: com.huawei.autoinstallapkfrommcc, PID: 5228
04-21 02:30:48.457  5228  5228 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.huawei.autoinstallapkfrommcc.InstallAPKReceiver: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3705)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1979)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7425)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:312)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.huawei.autoinstallapkfrommcc.InstallAPKReceiver.onReceive(InstallAPKReceiver.java:42)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3695)
</code></pre>

**Comment by ZoidbergZero** [comment]
This Error isnt Caused by this App.
When you run the App Please Search in the Logcat for "main" and Post the Output.

**Comment by ZoidbergZero** [comment]
Also No Links in the Comments Please.

**Comment by XAMIR555** [comment]
thanks for reopen my issue sir 

sir this is  latest Logcat here 

<pre><code> 04-27 03:16:51.402  6017  6017 E AndroidRuntime: FATAL EXCEPTION: main
04-27 03:16:51.402  6017  6017 E AndroidRuntime: Process: com.huawei.autoinstallapkfrommcc, PID: 6017
04-27 03:16:51.402  6017  6017 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.huawei.autoinstallapkfrommcc.InstallAPKReceiver: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3814)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2082)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:312)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at com.huawei.autoinstallapkfrommcc.InstallAPKReceiver.onReceive(InstallAPKReceiver.java:42)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3804)
04-27 03:16:51.402  6017  6017 E AndroidRuntime: 	... 8 more
</code></pre>

Here is Full logcat of my mobile 
[logcat.txt](https://github.com/ZoidbergZero/MusicMan/files/3124076/logcat.txt)

Thanks for your feedback  i believe you are a great developer 
GOD gives you more success
